# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='C:\\dja\x08log\\images\\%Y\\%m\\%d'),
        ),
    ]
