# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180226_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, height_field=100, upload_to='images/%Y/%m/%d', width_field=100),
        ),
    ]
