# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-26 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180226_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d', verbose_name='Картинка'),
        ),
    ]
